name: Run Terraform Checks
on:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - name: Configure AWS credentials for S3 state file access
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/MgmtDPBootstrapTerraformGitHubRepositoriesRole
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - name: Terraform Format
        id: fmt
        run: |
          terraform init
          terraform fmt -check --recursive
          terraform validate
